# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  #    param_fetcher_listener:  true
  #    allowed_methods_listener:  true
  #  routing_loader: true
  serializer:
    serialize_null: true
  view:
    view_response_listener: true
  #    exception:
  #        codes:
  #            App\Exception\MyException: 403
  #        messages:
  #            App\Exception\MyException: Forbidden area.
  format_listener:
    enabled: true
    rules:
      - { path: ^/api, prefer_extension: false, fallback_format: json, priorities: [ json ] }
      - { path: ^/raw, prefer_extension: false, fallback_format: json, priorities: [ json ] }
      - { path: ^/, priorities: [ html, '*/*' ], fallback_format: json, prefer_extension: true }
