nelmio_api_doc:
  documentation:
    info:
      title: Korona dáta zo Slovenska
      description: 'API má za cieľ združovať dáta z rôznych zdrojov, dobre ich štrukturovať a dokumentovať.
                    Ak máte pripomienky alebo otázky, tak prosím <a href="https://github.com/slovensko-help/data-korona/issues">vytvorte Issue</a>
                    alebo nám napíšte email na korona.gov@krizovystab.sk.
                    Celý projekt je open source, tak radi privítame aj pull requesty. <a href="https://github.com/slovensko-help/data-korona">GitHub</a>'
      version: 0.0.1
  #    components:
  #      securitySchemes:
  #        Bearer:
  #          type: http
  #          scheme: bearer
  #          bearerFormat: JWT
  #    security:
  #      - Bearer: [ ]
  areas:
    path_patterns:
      - ^/api(?!/doc$)