nelmio_api_doc:
  documentation:
    info:
      title: Korona dáta zo Slovenska
#      description: Various corona related data from Slovakia
      version: 0.0.1
#    components:
#      securitySchemes:
#        Bearer:
#          type: http
#          scheme: bearer
#          bearerFormat: JWT
#    security:
#      - Bearer: [ ]
  areas:
    path_patterns:
      - ^/api(?!/doc$)