<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20210927181440 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE slovakia_vaccinated_people (id VARCHAR(255) CHARACTER SET ascii NOT NULL, unvaccinated_ag_positives_rate INT DEFAULT NULL, fully_vaccinated_ag_positives_rate INT DEFAULT NULL, partially_vaccinated_ag_positives_rate INT DEFAULT NULL, unknown_ag_positives_rate INT DEFAULT NULL, unvaccinated_ag_negatives_rate INT DEFAULT NULL, fully_vaccinated_ag_negatives_rate INT DEFAULT NULL, partially_vaccinated_ag_negatives_rate INT DEFAULT NULL, unknown_ag_negatives_rate INT DEFAULT NULL, unvaccinated_pcr_positives_rate INT DEFAULT NULL, fully_vaccinated_pcr_positives_rate INT DEFAULT NULL, partially_vaccinated_pcr_positives_rate INT DEFAULT NULL, unknown_pcr_positives_rate INT DEFAULT NULL, unvaccinated_pcr_negatives_rate INT DEFAULT NULL, fully_vaccinated_pcr_negatives_rate INT DEFAULT NULL, partially_vaccinated_pcr_negatives_rate INT DEFAULT NULL, unknown_pcr_negatives_rate INT DEFAULT NULL, vaccinated_patients_rate INT DEFAULT NULL, unvaccinated_patients_rate INT DEFAULT NULL, unknown_patients_rate INT DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', published_on DATE NOT NULL COMMENT \'(DC2Type:date_immutable)\', INDEX IDX_ED75FFA43625D9F (updated_at), INDEX IDX_ED75FFA83352915 (published_on), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('DROP TABLE audit_district_ag_tests');
        $this->addSql('DROP TABLE audit_region_ag_tests');
        $this->addSql('DROP TABLE audit_region_vaccinations');
        $this->addSql('DROP TABLE audit_slovakia_ag_tests');
        $this->addSql('DROP TABLE audit_slovakia_vaccinations');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE audit_district_ag_tests (id INT UNSIGNED AUTO_INCREMENT NOT NULL, type VARCHAR(10) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, object_id VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, discriminator VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, transaction_hash VARCHAR(40) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, diffs LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, blame_id VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, blame_user VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, blame_user_fqdn VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, blame_user_firewall VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, ip VARCHAR(45) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX discriminator_b1140b2fc9cecd0019a76b0fc89dc19d_idx (discriminator), INDEX created_at_b1140b2fc9cecd0019a76b0fc89dc19d_idx (created_at), INDEX type_b1140b2fc9cecd0019a76b0fc89dc19d_idx (type), INDEX transaction_hash_b1140b2fc9cecd0019a76b0fc89dc19d_idx (transaction_hash), INDEX object_id_b1140b2fc9cecd0019a76b0fc89dc19d_idx (object_id), INDEX blame_id_b1140b2fc9cecd0019a76b0fc89dc19d_idx (blame_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE audit_region_ag_tests (id INT UNSIGNED AUTO_INCREMENT NOT NULL, type VARCHAR(10) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, object_id VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, discriminator VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, transaction_hash VARCHAR(40) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, diffs LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, blame_id VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, blame_user VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, blame_user_fqdn VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, blame_user_firewall VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, ip VARCHAR(45) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX discriminator_f7e212b86e46015c8979bf01fe8bde7b_idx (discriminator), INDEX created_at_f7e212b86e46015c8979bf01fe8bde7b_idx (created_at), INDEX type_f7e212b86e46015c8979bf01fe8bde7b_idx (type), INDEX transaction_hash_f7e212b86e46015c8979bf01fe8bde7b_idx (transaction_hash), INDEX object_id_f7e212b86e46015c8979bf01fe8bde7b_idx (object_id), INDEX blame_id_f7e212b86e46015c8979bf01fe8bde7b_idx (blame_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE audit_region_vaccinations (id INT UNSIGNED AUTO_INCREMENT NOT NULL, type VARCHAR(10) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, object_id VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, discriminator VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, transaction_hash VARCHAR(40) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, diffs LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, blame_id VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, blame_user VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, blame_user_fqdn VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, blame_user_firewall VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, ip VARCHAR(45) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX discriminator_4b413bdf344f891789676e6b4c62bc26_idx (discriminator), INDEX created_at_4b413bdf344f891789676e6b4c62bc26_idx (created_at), INDEX type_4b413bdf344f891789676e6b4c62bc26_idx (type), INDEX transaction_hash_4b413bdf344f891789676e6b4c62bc26_idx (transaction_hash), INDEX object_id_4b413bdf344f891789676e6b4c62bc26_idx (object_id), INDEX blame_id_4b413bdf344f891789676e6b4c62bc26_idx (blame_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE audit_slovakia_ag_tests (id INT UNSIGNED AUTO_INCREMENT NOT NULL, type VARCHAR(10) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, object_id VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, discriminator VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, transaction_hash VARCHAR(40) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, diffs LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, blame_id VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, blame_user VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, blame_user_fqdn VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, blame_user_firewall VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, ip VARCHAR(45) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX discriminator_85197a067c004af43d0de9e5257f95f3_idx (discriminator), INDEX created_at_85197a067c004af43d0de9e5257f95f3_idx (created_at), INDEX type_85197a067c004af43d0de9e5257f95f3_idx (type), INDEX transaction_hash_85197a067c004af43d0de9e5257f95f3_idx (transaction_hash), INDEX object_id_85197a067c004af43d0de9e5257f95f3_idx (object_id), INDEX blame_id_85197a067c004af43d0de9e5257f95f3_idx (blame_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE audit_slovakia_vaccinations (id INT UNSIGNED AUTO_INCREMENT NOT NULL, type VARCHAR(10) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, object_id VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, discriminator VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, transaction_hash VARCHAR(40) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, diffs LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, blame_id VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, blame_user VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, blame_user_fqdn VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, blame_user_firewall VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, ip VARCHAR(45) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX discriminator_39daea63de5c152a883369c67183e75e_idx (discriminator), INDEX created_at_39daea63de5c152a883369c67183e75e_idx (created_at), INDEX type_39daea63de5c152a883369c67183e75e_idx (type), INDEX transaction_hash_39daea63de5c152a883369c67183e75e_idx (transaction_hash), INDEX object_id_39daea63de5c152a883369c67183e75e_idx (object_id), INDEX blame_id_39daea63de5c152a883369c67183e75e_idx (blame_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('DROP TABLE slovakia_vaccinated_people');
    }
}
