<?php

declare(strict_types=1);

namespace App\Repository;

use App\Entity\District;
use App\Entity\Region;
use Doctrine\Persistence\ManagerRegistry;

/**
 * @method District|null find($id, $lockMode = null, $lockVersion = null)
 * @method District|null findOneBy(array $criteria, array $orderBy = null)
 * @method District[]    findAll()
 * @method District[]    findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
 */
class DistrictRepository extends AbstractRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, District::class);
    }

//    public function save(District $district, Region $region)
//    {
//        $district->setRegion($region);
//
//        parent::save($item, $relatedEntities); // TODO: Change the autogenerated stub
//    }
}
