monolog:
    channels: ['ncziProxy']
    handlers:
        nczi_proxy:
            level: info
            type: stream
            path: '%kernel.logs_dir%/nczi_proxy.log'
            channels: [ ncziProxy ]
